### PR TITLE
Add cashflow ScheduledInternalRateOfReturn

### PR DESCRIPTION
**Pull request by brunoyb**
This is the implementation of Excel's XIRR function. It is very similar
to IRR, the only difference being that this one takes payment dates into
account.

I also took the opportunity to make a small simplification to
dNetPresentValue's formula.

See: https://support.office.com/en-us/article/xirr-function-de1242ec-6477-445b-b11b-a303ad9adc9d
See: https://support.office.com/en-us/article/xnpv-function-1b42bbf6-370f-4532-a0eb-d67c16b664b7

### CODE REVIEW

**Comment by brunoyb** [comment]
Hi! I found your library and it is very useful, thank you! I also needed the XIRR function, so I decided to contribute it, so here is my implementation.

Feel free to comment on anything you think should be changed.

Thanks again for creating this library!

**Comment by alpeb** [comment]
Thank you so much @brunoyb !
I'll be taking a look in the next couple of days :+1:

**Comment by brunoyb** [comment]
Oh, and I forgot to mention, I based this implementation on this Rust version: https://github.com/cskr/xirr/blob/master/src/lib.rs I tried to make the necessary changes to follow the patterns of your project.

**Comment by rv-vsilva** [comment]
+1

**Review by alpeb — APPROVED** [review]
This looks awesome, thank you very much @brunoyb !

Thanks for the additional tests, updating the Readme, simplifying `dNetPresentValue` and following the style from the other functions :+1:

**Comment by brunoyb** [comment]
Hey! Awesome! Glad I could help!

**Pull request merged**
